import { resolve } from 'node:path';

import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

// The shared component library and design tokens are adopted from
// boost-library and consumed as source out of libs/ — no build step.
const lib = (p: string) => resolve(import.meta.dirname, '../../libs', p);

export default defineConfig({
  plugins: [tailwindcss(), react()],
  resolve: {
    alias: {
      '@boost/ui': lib('ui/src/index.ts'),
      '@boost/styles': lib('styles/src'),
      // Source, not dist: api.gen.ts is regenerated by `nx run shared:codegen`,
      // and editing the aliases hot-reloads instead of waiting on a tsc build.
      '@rag/shared': lib('shared/src/index.ts'),
    },
    // Single React instance — @boost/ui carries its own Radix/lucide deps
    // whose React peer could otherwise resolve to a second copy.
    dedupe: ['react', 'react-dom'],
  },
  server: {
    port: 5300,
    fs: { allow: [resolve(import.meta.dirname, '../..')] },
    proxy: {
      '/api': {
        target: 'http://localhost:3300',
        changeOrigin: true,
        // uvicorn drops briefly while it reloads; answer 502 rather than
        // letting the proxy error take down the Vite server.
        configure: (proxy) => {
          proxy.on('error', (_err, _req, res) => {
            const r = res as import('node:http').ServerResponse | undefined;
            if (r && 'writeHead' in r && !r.headersSent) {
              r.writeHead(502, { 'content-type': 'application/json' });
              r.end(JSON.stringify({ detail: 'api unavailable (restarting)' }));
            }
          });
        },
      },
    },
  },
});
